### ISSUE TITLE
Error when running the test_phases.py example

### ISSUE THREAD

**Issue by simon-sat** [junzis/flight-data-processor#4]
Hello, I've just discovered this toolkit - which looks really useful...but I have run into a problem:
I'm trying to run the test_phases example file and am running into an error (see below). This also happens with my own data: It seems that the `labels` array returned by `fuzzylabels` is larger than the original data arrays.
Any ideas what could be happening here? I will investigate this myself but thought I'd create an issue in case you have a quick insight into what went wrong.

```Traceback (most recent call last):
  File "/home/s/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4291, in _parse_scatter_color_args
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_phases.py", line 38, in <module>
    plt.scatter(times, alts, marker='.', c=colors, lw=0)
  File "/home/s/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2847, in scatter
    None else {}), **kwargs)
  File "/home/s/miniconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1601, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/s/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4454, in scatter
    get_next_color_func=self._get_patches_for_fill.get_next_color)
  File "/home/s/miniconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4298, in _parse_scatter_color_args
    .format(nc=n_elem, xs=xsize, ys=ysize)
ValueError: 'c' argument has 1048 elements, which is not acceptable for use with 'x' with size 934, 'y' with size 934.
```

This is with a `python 3.7.3` conda environment with the following library versions:
`numpy 1.17.0`
`scikit-fuzzy 0.4.1`
`matplotlib 3.1.1`
`scipy 1.3.0`

**Comment by simon-sat** [comment]
Closed with PR #5
